services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: ./fast-image-sse
    container_name: api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  worker-resize:
    build: ./worker-sqs
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: resize
      SQS_URL: https://sqs.us-east-1.amazonaws.com/544295977234/MyQueue-resize
    depends_on:
      - redis

  worker-thumbnail:
    build: ./worker-sqs
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: thumbnail
      SQS_URL: https://sqs.us-east-1.amazonaws.com/544295977234/MyQueue-thumbnail
    depends_on:
      - redis

  worker-filter:
    build: ./worker-sqs
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: filter
      SQS_URL: https://sqs.us-east-1.amazonaws.com/544295977234/MyQueue-filter
    depends_on:
      - redis

  worker-convert:
    build: ./worker-sqs
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: convert
      SQS_URL: https://sqs.us-east-1.amazonaws.com/544295977234/MyQueue-convert
    depends_on:
      - redis
